version: '3'

services:
  postgres:
    networks:
      - net
    volumes:
      - ./../postgresql/data-10.0:/var/lib/postgresql/data
    environment: &postgres_env
      POSTGRES_DB: KEY
      POSTGRES_USER: KEY
      POSTGRES_PASSWORD: KEY

  redis:
    networks:
      - net

  frontend:
    build:
      args:
        BRANCH: master
    ports:
      - 4200:4200
    networks:
      - net
    volumes:
      - ./../frontend:/frontend
    environment:
      TERM: xterm-256color
      API_HOSTNAME: localhost:3000
      WEBPACK_BUILD_ENV: development

  backend:
    build:
      args:
        BRANCH: master
    volumes:
      - .:/backend
    ports:
      - 3000:3000
    networks:
      - net
    environment: &backend_env
      REDIS_URL: redis://redis:6379/1
      POSTGRES_HOST: postgres
      RAILS_ENV: development

  sidekiq:
    volumes:
      - .:/backend
    networks:
      - net
    command: ./docker-entrypoint.sh
    environment:
      <<: *backend_env
      SERVICE_NAME: sidekiq

  helper:
    volumes:
      - .:/backend
    networks:
      - net
    command: ./docker-entrypoint.sh
    environment:
      <<: *backend_env
      SERVICE_NAME: helper

networks:
  net:
    ipam:
      driver: default
