version: '3.3'

services:
  postgres:
    networks:
      - net
    volumes:
      - ./../postgresql/data:/var/lib/postgresql/data
    environment: &postgres_env
      POSTGRES_DB: DB
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD

  redis:
    networks:
      - net

  frontend:
    networks:
      - net
    ports:
      - 4200:4200
    volumes:
      - ./../frontend:/frontend
    environment:
      TERM: xterm-256color
      API_HOSTNAME: localhost:3000
      WEBPACK_BUILD_ENV: development

  backend:
    networks:
      - net
    ports:
      - 3000:3000
    volumes:
      - .:/backend
    environment: &backend_env
      <<: *postgres_env
      SECRET_KEY_BASE: SECRET_KEY_BASE
      REDIS_URL: redis://redis:6379/1
      POSTGRES_HOST: postgres
      TERM: xterm-256color
      RAILS_ENV: development
      HOSTNAME: localhost:3000
      SOME_KEY: KEY

  sidekiq:
    networks:
      - net
    volumes:
      - .:/backend
    environment:
      <<: *backend_env

networks:
  net:
    ipam:
      driver: default
