version: '2'

services:
  postgres:
    environment:
      POSTGRES_DB: PROJECT
      POSTGRES_USER: PROJECT
      POSTGRES_PASSWORD: PROJECT

  nginx:
    build:
      args:
        env: prod

  frontend:
    build:
      args:
        branch: master
        repository: FRONTEND_REPOSITORY_ADDRESS
    environment:
      WEBPACK_BUILD_ENV: prod

  backend:
    build:
      args:
        branch: master
        repository: BACKEND_REPOSITORY_ADDRESS
    environment:
      HOSTNAME: HOSTNAME
      RAILS_ENV: production
      REDIS_URL: redis
      POSTGRES_HOST: postgres
      POSTGRES_DB: PROJECT
      POSTGRES_USER: PROJECT
      POSTGRES_PASSWORD: PROJECT

  sidekiq:
    environment:
      HOSTNAME: HOSTNAME
      RAILS_ENV: production
      REDIS_URL: redis
      POSTGRES_HOST: postgres
      POSTGRES_DB: PROJECT
      POSTGRES_USER: PROJECT
      POSTGRES_PASSWORD: PROJECT
