version: '3.3'

services:
  postgres:
    image: postgres:10.0-alpine
    expose:
      - 5432

  redis:
    image: redis:4.0-alpine
    expose:
      - 6379

  frontend:
    build:
      context: ./docker/frontend/
      dockerfile: Dockerfile
    image: PROJECT/frontend
      args:
        REPOSITORY: git@github.com:user/repository.git
    entrypoint: ./docker-entrypoint.sh
    stop_signal: SIGKILL # The only signal working for node

  backend:
    build:
      context: ./docker/backend/
      dockerfile: Dockerfile
      args:
        REPOSITORY: git@github.com:user/repository.git
    image: PROJECT/backend
    depends_on:
      - postgres
      - redis
    entrypoint: ./docker-entrypoint.sh
    stop_signal: SIGINT # Puma's waiting it to quit with 0

  sidekiq:
    image: PROJECT/backend
    depends_on:
      - postgres
      - redis
    command: sh -c './docker.db-check.sh && exec bundle exec sidekiq' # Do not forget to execute last comand with exec to let sidekiq have PID 1
