version: '3'

services:
  postgres:
    image: postgres:10-alpine
    expose:
      - 5432

  redis:
    image: redis:4.0-alpine
    expose:
      - 6379

  frontend:
    build:
      context: ./docker/frontend/
      dockerfile: Dockerfile
    image: PROJECT/frontend
    command: ./docker-entrypoint.sh
    stop_signal: SIGKILL

  backend:
    build:
      context: ./docker/backend/
      dockerfile: Dockerfile
    image: PROJECT/backend
    command: ./docker-entrypoint.sh
    stop_signal: SIGINT

  sidekiq:
    image: PROJECT/backend
    command: ./docker-entrypoint.sh

  helper:
    image: PROJECT/backend
    command: ./docker-entrypoint.sh
