version: '3.3'

services:
  postgres:
    image: postgres:10.0-alpine
    expose:
      - 5432

  redis:
    image: redis:4.0-alpine
    expose:
      - 6379

  frontend:
    build:
      context: ./docker/frontend/
      dockerfile: Dockerfile
    image: PROJECT/frontend
      args:
        REPOSITORY: git@github.com:user/repository.git
    command: sh -c './docker-entrypoint.sh'

  backend:
    build:
      context: ./docker/backend/
      dockerfile: Dockerfile
      args:
        REPOSITORY: git@github.com:user/repository.git
    image: PROJECT/backend
    depends_on:
      - postgres
      - redis
    command: sh -c './docker-entrypoint.sh'

  sidekiq:
    image: PROJECT/backend
    depends_on:
      - postgres
      - redis
    command: sh -c './docker.db-check.sh && bundle exec sidekiq'
