version: '2'

services:
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - "5432"
    volumes:
      - /var/www/PROJECT/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    restart: always
    ports:
      - "6379"

  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    image: PROJECT-nginx
    restart: always
    volumes:
      - /var/www/PROJECT/frontend:/frontend
      - /var/www/PROJECT/backend/tmp/sockets:/sockets
      - /var/www/PROJECT/backend/log:/log
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  frontend:
    build:
      context: ./docker/frontend/
      dockerfile: Dockerfile
    image: PROJECT-frontend
    volumes:
      - /var/www/PROJECT/frontend:/dist
    command: sh -c "ng build --target=production --environment="$WEBPACK_BUILD_ENV" && rm -rf /dist/* && cp -r /frontend/dist/* /dist/"

  backend:
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    image: PROJECT-backend
    restart: always
    volumes:
      - /var/www/PROJECT/backend/tmp/sockets:/backend/tmp/sockets
      - /var/www/PROJECT/backend/log:/backend/log
    command: sh -c "sleep 5 && bundle exec rake db:migrate && bundle exec puma --config config/puma.rb"
    links:
      - postgres
      - redis
      - nginx

  sidekiq:
    image: PROJECT-backend
    restart: always
    command: sh -c "sleep 5 && bundle exec sidekiq"
    links:
      - postgres
      - redis
