default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  hostname: <%= ENV['HOSTNAME'] %>
  some_key: <%= ENV['SOME_KEY'] %>

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
